# Generated by Django 5.1.6 on 2025-03-03 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('board', models.CharField(default='         ', max_length=9)),
                ('current_player', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('game_over', models.BooleanField(default=False)),
                ('game_mode', models.CharField(default='online', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
