# Generated by Django 5.1.6 on 2025-03-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictac', '0002_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, null=True, verbose_name='accounts.MyUser'),
        ),
    ]
