# Generated by Django 5.1.6 on 2025-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictac', '0009_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='last_game_id',
            field=models.IntegerField(default=0),
        ),
    ]
