# Generated by Django 5.1.6 on 2025-03-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictac', '0010_gamestats_last_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='last_game_id',
        ),
    ]
