# Generated by Django 5.1.6 on 2025-03-03 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('ON', 'Online Match')], max_length=20)),
                ('match_score', models.CharField(max_length=10)),
                ('user_status', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
