# Generated by Django 5.1.6 on 2025-03-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
